import React from 'react';
import { TokenomicsChart } from './TokenomicsChart';

export const Whitepaper: React.FC = () => {
  return (
    <div className="min-h-screen bg-cyber-dark text-white p-6 pb-32 font-sans overflow-y-auto selection:bg-cyber-pink selection:text-black">
      
      {/* Header */}
      <div className="relative mb-12 mt-4 border-b border-cyber-dim/50 pb-6">
        <h1 className="text-4xl font-black tracking-tighter text-transparent bg-clip-text bg-gradient-to-r from-white via-cyber-cyan to-white animate-shimmer bg-[length:200%_auto]">
          WYYRRDDD PROTOCOL
        </h1>
        <p className="text-cyber-dim font-mono text-xs tracking-[0.3em] mt-2 uppercase">
          Technical Whitepaper v1.0
        </p>
        <div className="absolute -bottom-[1px] left-0 w-1/3 h-[2px] bg-cyber-cyan shadow-[0_0_10px_#00F0FF]" />
      </div>

      {/* Abstract */}
      <section className="mb-12 relative">
        <div className="absolute -left-4 top-0 w-[2px] h-full bg-gradient-to-b from-cyber-pink to-transparent" />
        <h2 className="text-xl font-bold text-cyber-pink mb-4 flex items-center gap-2">
          <span className="text-xs font-mono opacity-50">01.</span> ABSTRACT
        </h2>
        <p className="text-sm text-gray-300 leading-relaxed font-light">
          Wyyrrddd is a decentralized social coordination layer built on Polkadot, designed to monetize user attention and interaction data directly. By tokenizing social signals (LIKE, LOVE, CARE, CREEP) into liquid assets, Wyyrrddd creates a closed-loop economy where reputation is currency and data sovereignty is enforced by the Wyrd Data DAO.
        </p>
      </section>

      {/* The Problem */}
      <section className="mb-12">
        <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
          <span className="text-xs font-mono text-cyber-dim">02.</span> THE FRAGMENTATION
        </h2>
        <div className="bg-cyber-panel border border-cyber-dim p-4 rounded-sm relative overflow-hidden">
          <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-10 mix-blend-overlay" />
          <p className="text-xs text-gray-400 font-mono mb-2">
            &gt;&gt; Web2 social graphs capture 100% of value generated by user interactions.
          </p>
          <p className="text-xs text-gray-400 font-mono">
            &gt;&gt; Users provide labor (content, curation) for zero equity.
          </p>
        </div>
      </section>

      {/* Tokenomics */}
      <section className="mb-12">
        <h2 className="text-xl font-bold text-cyber-cyan mb-6 flex items-center gap-2">
          <span className="text-xs font-mono opacity-50">03.</span> TOKENOMICS
        </h2>
        
        <TokenomicsChart />

        <div className="grid grid-cols-2 gap-4 mt-6">
          <div className="p-3 border border-cyber-dim bg-cyber-black/50">
            <h3 className="text-cyber-cyan font-bold text-xs mb-1">LIKE (Utility)</h3>
            <p className="text-[10px] text-gray-500">High-velocity signal token. Used for basic reach boosting.</p>
          </div>
          <div className="p-3 border border-cyber-dim bg-cyber-black/50">
            <h3 className="text-cyber-pink font-bold text-xs mb-1">LOVE (Gov)</h3>
            <p className="text-[10px] text-gray-500">Governance weight. Earned by top 1% content creators.</p>
          </div>
          <div className="p-3 border border-cyber-dim bg-cyber-black/50">
            <h3 className="text-cyber-yellow font-bold text-xs mb-1">CARE (Yield)</h3>
            <p className="text-[10px] text-gray-500">Staking reward token. Earned by curating high-quality posts.</p>
          </div>
          <div className="p-3 border border-cyber-dim bg-cyber-black/50">
            <h3 className="text-purple-400 font-bold text-xs mb-1">CREEP (Rep)</h3>
            <p className="text-[10px] text-gray-500">Negative reputation / privacy tax. Costs DOT to burn.</p>
          </div>
        </div>
      </section>

      {/* Roadmap */}
      <section className="mb-8">
        <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
          <span className="text-xs font-mono text-cyber-dim">04.</span> EXECUTION PLAN
        </h2>
        <div className="space-y-4 border-l border-cyber-dim/30 pl-6 ml-2">
          <div className="relative">
            <div className="absolute -left-[29px] top-1.5 w-3 h-3 rounded-full bg-cyber-cyan shadow-[0_0_10px_#00F0FF]" />
            <h3 className="text-sm font-bold text-white">Phase 1: Genesis (MVP)</h3>
            <p className="text-xs text-gray-500 mt-1">Local-first simulation, Polkadot wallet connect, basic interaction mining.</p>
          </div>
          <div className="relative opacity-60">
            <div className="absolute -left-[29px] top-1.5 w-3 h-3 rounded-full border border-cyber-dim bg-cyber-black" />
            <h3 className="text-sm font-bold text-white">Phase 2: The Weave</h3>
            <p className="text-xs text-gray-500 mt-1">On-chain event logging, ink! smart contracts for Data DAO.</p>
          </div>
          <div className="relative opacity-40">
            <div className="absolute -left-[29px] top-1.5 w-3 h-3 rounded-full border border-cyber-dim bg-cyber-black" />
            <h3 className="text-sm font-bold text-white">Phase 3: Ragnarök</h3>
            <p className="text-xs text-gray-500 mt-1">Full decentralization, token TGE, global geospatial raids.</p>
          </div>
        </div>
      </section>

    </div>
  );
};

